language: python
python:
  - "3.6"
install:
  - pip install pytest
  - pip install pytest-cov
  - pip install coveralls
script:
  - pip install -r requirements.txt
  - pytest --cov=kwcom/
after_success:
  - coveralls
